
package com.vladimirg.wst.lab1_client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InstrumentWebService", targetNamespace = "http://lab1_server.wst.vladimirg.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InstrumentWebService {


    /**
     * 
     * @return
     *     returns java.util.List<com.vladimirg.wst.lab1_client.Instrument>
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllInstruments", targetNamespace = "http://lab1_server.wst.vladimirg.com/", className = "com.vladimirg.wst.lab1_client.GetAllInstruments")
    @ResponseWrapper(localName = "getAllInstrumentsResponse", targetNamespace = "http://lab1_server.wst.vladimirg.com/", className = "com.vladimirg.wst.lab1_client.GetAllInstrumentsResponse")
    @Action(input = "http://lab1_server.wst.vladimirg.com/InstrumentWebService/getAllInstrumentsRequest", output = "http://lab1_server.wst.vladimirg.com/InstrumentWebService/getAllInstrumentsResponse", fault = {
        @FaultAction(className = SQLException_Exception.class, value = "http://lab1_server.wst.vladimirg.com/InstrumentWebService/getAllInstruments/Fault/SQLException")
    })
    public List<Instrument> getAllInstruments()
        throws SQLException_Exception
    ;

    /**
     * 
     * @param mic
     * @param validUntil
     * @param derivative
     * @param id
     * @param isin
     * @return
     *     returns java.util.List<com.vladimirg.wst.lab1_client.Instrument>
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getInstruments", targetNamespace = "http://lab1_server.wst.vladimirg.com/", className = "com.vladimirg.wst.lab1_client.GetInstruments")
    @ResponseWrapper(localName = "getInstrumentsResponse", targetNamespace = "http://lab1_server.wst.vladimirg.com/", className = "com.vladimirg.wst.lab1_client.GetInstrumentsResponse")
    @Action(input = "http://lab1_server.wst.vladimirg.com/InstrumentWebService/getInstrumentsRequest", output = "http://lab1_server.wst.vladimirg.com/InstrumentWebService/getInstrumentsResponse", fault = {
        @FaultAction(className = SQLException_Exception.class, value = "http://lab1_server.wst.vladimirg.com/InstrumentWebService/getInstruments/Fault/SQLException")
    })
    public List<Instrument> getInstruments(
        @WebParam(name = "id", targetNamespace = "")
        Integer id,
        @WebParam(name = "MIC", targetNamespace = "")
        String mic,
        @WebParam(name = "ISIN", targetNamespace = "")
        String isin,
        @WebParam(name = "validUntil", targetNamespace = "")
        XMLGregorianCalendar validUntil,
        @WebParam(name = "derivative", targetNamespace = "")
        Boolean derivative)
        throws SQLException_Exception
    ;

}
